### ISSUE TITLE
vagrant up trusty fails

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#147]
first problem: abunchofthings.net on https gives an annoying gnutls handshake failure.
tweaking out https to http seems to bypass that.
second problem: libgd-perl dependency not installed.

**Comment by mtompset** [comment]
manually installing libgd-perl and reprovisioning seems to get playbook continuing.

**Comment by mtompset** [comment]
TASK [kohadevbox : Install testing dependencies (cpanm)] ***********************
changed: [trusty] => (item=HTTPD::Bench::ApacheBench)
failed: [trusty] (item=Test::DBIx::Class) => {"cmd": "/usr/bin/cpanm Test::DBIx::Class --mirror http://mirror.cc.columbia.edu/pub/software/cpan", "failed": true, "item": "Test::DBIx::Class", "msg": "! Installing Type::Tiny failed. See /root/.cpanm/work/1482365836.20505/build.log for details. Retry with --force to force install it.\n! Installing the dependencies failed: Module 'Type::Tiny' is not installed\n! Bailing out the installation for DBIx-Class-Schema-PopulateMore-0.19.\n! Installing the dependencies failed: Module 'DBIx::Class::Schema::PopulateMore' is not installed\n! Bailing out the installation for Test-DBIx-Class-0.52.\n"}

**Comment by tomascohen** [comment]
@mtompset dependencies are not kohadevbox's responsability. We could add an exception so it installs the required package manually, but we don't support Trusty anymore anyway.

Regarding Test::DBIx::Class, try choosing a different CPAN mirror on vars/user.yml

**Comment by mtompset** [comment]
If Trusty isn't supported, then the Vagrant file shouldn't have it,.

**Comment by tomascohen** [comment]
Trusty isn't supported by current Koha master packages. I left the option to launch kohadevbox with Trusty as a basis, because you can tweak the repository you install the packages from to whatever you want, and you might well have your own (say) 3.22.x build you want to test. (see vars/user.yml and the repository options)

For example, I still support a couple 3.22 setups, and provide deb http://theke.io/debian/koha 3.22 main for that, and it is handy to have it installed on a special kohadevbox to test it.

**Comment by tomascohen** [comment]
Also, if you have ideas of how to make trusty load with an usable setup, I accept pull requests for that.
