### ISSUE TITLE
When provisioned without $SYNC_REPO, /home/vagrant/kohaclone is owned by root.

### ISSUE THREAD

**Issue by bartonski** [digibib/kohadevbox#179]
When running `git qa 123456` I get the error message

    cannot open .git/FETCH_HEAD: Permission denied

This is caused by `/home/vagrant/kohaclone` being owned by root. `sudo git qa 123456` fails because root does not have the `git qa` alias set up.

I believe that this could be fixed by adding `become_user: vagrant` to `roles/kohadevbox/tasks/koha-src.yml`:

    - name: Koha source | Clone repository
      git:
        repo: "{{ koha_git_repo }}"
        dest: /home/vagrant/kohaclone
        version: "{{ koha_git_branch }}"
        become_user: vagrant
      when: not sync_repo

Note: this is untested, and I'm not *entirely* sure whether `become_user: vagrant`
 should be inside the `git:` block or a level higher.

**Comment by tomascohen** [comment]
Ok, this problem comes from the fact that we've been running everything as root from the begining. I'll provide a patch for this right now. It should fix other permissions issues reported randomly on IRC and koha-devel for a while. We now have a more fine-grained organization of the tasks. It is just a matter to tracking every action and the needed permissions.

**Comment by tomascohen** [comment]
Done!
