### ISSUE TITLE
plack doesn't use dev env

### ISSUE THREAD

**Issue by ohait** [digibib/kohadevbox#181]
/etc/default/koha-common set KOHA_HOME to
/usr/share/koha and nothing replace it on the way down to plack,
resulting in starman using debian files for the CGIs

i'm not sure which script should set the ENV properly, but if i run:

$ sudo -u kohadev-koha KOHA_CONF=/etc/koha/sites/kohadev/koha-conf.xml
KOHA_HOME=/home/vagrant/kohaclone/ DEV_INSTALL=1 starman --socket
/var/run/koha/kohadev/plack.sock debian/templates/plack.psgi

so i guess something went missing during the setup/provisioning

**Comment by tomascohen** [comment]
@ohait can you explain how you check the used lib? I ask this because of the following snippet in:

`
koha-plack:284             adjust_paths_dev_install $name
`
adjust_paths_dev_install is defined in koha-functions.sh:
`
adjust_paths_dev_install()
{
# Adjust KOHA_HOME, PERL5LIB for dev installs, as indicated by
# corresponding tag in koha-conf.xml

    local instancename=$1
    local dev_install=""

    if [ "$instancename" != "" ] && is_instance $instancename; then
        dev_install=$(run_safe_xmlstarlet $instancename dev_install)
    fi

    if [ "$dev_install" != "" ] && [ "$dev_install" != "0" ]; then
        DEV_INSTALL=1
        KOHA_HOME=$(run_safe_xmlstarlet $instancename intranetdir)
        PERL5LIB=$KOHA_HOME
    else
        DEV_INSTALL=""
    fi
}
`

**Comment by ohait** [comment]
I noticed because the code was different, but I doublechecked by adding a warning and seeing the filename of the .pm file in /usr/share/koha

I can check again why koha-functions.sh isn't enabling KOHA_HOME and DEV_INSTALL properly, so you will have more insight, next week.

**Comment by tomascohen** [comment]
You are missing <dev_install>1</dev_install> in the instance's koha-conf.xml file (located in /etc/koha/sites/kohadev/koha-conf.xml) and that's why it is not picking the right paths.

I didn't notice it, because I always used KOHA_ELASTICSEARCH=1 when creating the box, which pulls the right koha-conf.xml file.

You can add <dev_install>1</dev_install> to the file and move on. Or wait for the commit I'm about to do and then:

```
cd kohadevbox
git pull
SKIP_WEBINSTALLER=1 CREATE_ADMIN_USER=1 vagrant up
```
Whatever you prefer :-D

**Comment by tomascohen** [comment]
Done.
