### ISSUE TITLE
Modern::Perl is dependency of gitify

### ISSUE THREAD

**Issue by jganseman** [digibib/kohadevbox#98]
Kohadevbox breaks at gitify because Modern::Perl is not installed. Needs to be added as dependency? :
> sudo cpan Modern::Perl

**Comment by tomascohen** [comment]
This is already fixed in master. Thanks for reporting @jganseman.

As a side note, notice that Modern::Perl is already packaged in Debian (under the libmodern-perl-perl package name) and also that there's a meta-package for installing Koha's Perl dependencies. Next time, install Perl deps by issuing:

` $ sudo apt-get install koha-perldeps`

After that, take care of the missing ones using `apt-cache search <name>` to try installing using the packaging manager.

Thanks!
