### ISSUE TITLE
Missing perl dependencies?

### ISSUE THREAD

**Issue by jganseman** [digibib/kohadevbox#99]
After a clean build, koha won't appear online since many perl dependencies were still missing. Inside kohadevbox had to first manually run
> perl kohl_perl_deps.pl -m -u

After which I could install most of the listed dependencies by
> sudo cpan XXX::YYY

And for those that did not work sometimes this fixed it:
> sudo apt-find XXX::YYY
> sudo apt-get install libxxx-yyy-perl

Not sure whether I maybe missed or time-outed on something during the setup though (it took an entire night, getting the koha repo...)

**Comment by tomascohen** [comment]
Hi @jganseman, are you using the latest pull from master? There has been a major revamp of kohadevbox lately.
Please make sure you have the latest master and you have followed the README.md regarding the initial setup.

Provisioning (setting all we need on the VM) can sometimes fail due to timeout, notably installing Test::DBIx::Class. But fortunately you can re-provision the box by issuing

vagrant provision

If you already did all this, and you still cannot have it running properly, please let me know. And specify what operating system is yours installing.

Regards

**Comment by tomascohen** [comment]
@jganseman thanks for reporting this. I just had the chance to try it myself and found that current 'unstable' packages (those used to create this kohadevbox) were failing to pull the perl deps. This is fixed in latest master now.
